AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  GitHubToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /GitHub/AccessToken

Resources:
  YourCodePipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: YourCodePipelineRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "codepipeline.amazonaws.com"
            Action: "sts:AssumeRole"
  MyCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: MyCodePipeline
      RoleArn: !GetAtt YourCodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: developeramarkumar
                Repo: cloudformation
                Branch: main
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: SourceOutput
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                StackName: MyStack
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt YourCodePipelineRole.Arn
                TemplatePath: SourceOutput::deploy.yml
                Capabilities: CAPABILITY_IAM
              InputArtifacts:
                - Name: SourceOutput
