AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  GitHubToken:
    Type: String
    Description: "GitHub personal access token "

Resources:
  MyCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: MyCodePipeline
      RoleArn: <IAM Role ARN for CodePipeline>
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: <GitHub repo owner>
                Repo: <GitHub repo name>
                Branch: main
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: SourceOutput
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                StackName: MyStack
                ActionMode: CREATE_UPDATE
                RoleArn: <IAM Role ARN for CloudFormation>
                TemplatePath: SourceOutput::deploy.yml
                Capabilities: CAPABILITY_IAM
              InputArtifacts:
                - Name: SourceOutput
