name: Deploy CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # - name: Deploy CloudFormation http-template.yml
      #   run: |
      #     aws cloudformation deploy \
      #       --stack-name HttpLambdaStack \
      #       --template-file http-template.yml \
      #       --capabilities CAPABILITY_IAM

      # - name: Deploy CloudFormation rest-template.yml
      #   run: |
      #     aws cloudformation deploy \
      #       --stack-name RestLambdaStack \
      #       --template-file rest-template.yml \
      #       --capabilities CAPABILITY_IAM
      - name: Deploy CloudFormation  codepipeline-template.yml
        run: |
          aws cloudformation deploy \
            --stack-name MyCodePipelineStack \
            --template-file codepipeline-template.yml \
            --capabilities CAPABILITY_NAMED_IAM
