name: Deploy CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: mgenteluci/cloudformation-deploy-action@v1.4.1
        env:
          TEMPLATE: 'template.yml'
          AWS_STACK_NAME: 'my-stack'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}